#!/usr/bin/env python

import sys
from cv.face_tracking import FaceTracking
import chrome_app.chrome_message as chrome_message


if __name__ == '__main__':

    face_detected = False
    face_tracking = FaceTracking()
    while True:
        # if !face_detected and face_tracking.detect_faces():
        if face_tracking.detect_faces():
            face_detected = True
            chrome_message.send_message('{"echo": "face_detected"}')

    sys.exit(0)
