jokes = [
    "What time did the man go to the dentist? Tooth hurt-y.",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "You're American when you go into the bathroom, and you're American when you come out, but do you know what you are while you're in there? European.",
    "Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.",
    "Want to hear a joke about a piece of paper? Never mind... it's tearable.",
    "I just watched a documentary about beavers. It was the best dam show I ever saw!",
    "If you see a robbery at an Apple Store does that make you an iWitness?",
    "Spring is here! I got so excited I wet my plants!",
    "What's Forrest Gump's password? 1forrest1",
    "Did you hear about the guy who invented Lifesavers? They say he made a mint.",
    "I bought some shoes from a drug dealer. I don't know what he laced them with, but I was tripping all day!",
    "Why do chicken coops only have two doors? Because if they had four, they would be chicken sedans!",
    "What do you call a factory that sells passable products? A satisfactory.",
    "How do you make a Kleenex dance? Put a little boogie in it!",
    "When a dad drives past a graveyard: Did you know that's a popular cemetery? Yep, people are just dying to get in there!",
    "Two peanuts were walking down the street. One was a salted.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "I used to have a job at a calendar factory but I got the sack because I took a couple of days off.",
    "How do you make holy water? You boil the hell out of it.",
    "I had a dream that I was a muffler last night. I woke up exhausted!",
    "Did you hear the news? FedEx and UPS are merging. They're going to go by the name Fed-Up from now on.",
    "5/4 of people admit that they're bad with fractions.",
    "What is Beethoven's favorite fruit? A ba-na-na-na.",
    "Two guys walk into a bar, the third one ducks.What do you call a masturbating cow? Beef Stroganoff.",
    "Did you hear about the circus fire? It was in tents!",
    "Don't trust atoms. They make up everything!",
    "What do you call a cow with two legs? Lean beef. If the cow has no legs, then it's ground beef.",
    "What do you get when you cross an elephant with a rhino? Elephino.",
    "How many tickles does it take to make an octopus laugh? Ten-tickles.",
    "I'm only familiar with 25 letters in the English language. I don't know why.",
    "When a dad drives past a cow pasture: LOOK! That cow is OUT-STANDING in his field!",
    "What's the best part about living in Switzerland? I don't know, but the flag is a big plus.",
    "What do prisoners use to call each other? Cell phones.",
    "Why couldn't the bike standup by itself? It was two tired.",
    "What do you call a dog that can do magic? A Labracadabrador.",
    "Why didn't the vampire attack Taylor Swift? She had bad blood.",
    "The fattest knight at King Arthur's round table was Sir Cumference. He acquired his size from too much pi.",
    "Did you see they made round bails of hay illegal in Wisconsin? It's because the cows weren't getting a square meal.",
    "What do you call a fish with two knees? A \"two-knee\" fish.",
    "You know what the loudest pet you can get is? A trumpet.",
    "I was interrogated over the theft of a cheese toastie. Man, they really grilled me.",
    "What do you get when you cross a snowman with a vampire? Frostbite.",
    "What do you call a deer with no eyes? No idea!",
    "Can February March? No, but April May!",
    "What do you call a lonely cheese? Provolone.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the pee is silent.",
    "What does a zombie vegetarian eat? \"GRRRAAAAAIIIINNNNS!\"",
    "What does an angry pepper do? It gets jalapeño your face.",
    "Why wasn't the woman happy with the velcro she bought? It was a total ripoff.",
    "What did the buffalo say to his son when he dropped him off at school? Bison.",
    "What do you call someone with no body and no nose? Nobody knows.",
    "Where did the college-aged vampire like to shop? Forever 21.",
    "You heard of that new band 1023MB? They're good but they haven't got a gig yet.",
    "Why did the crab never share? Because he's shellfish."
]
